version: '3.8'
services:
  db:
    image: postgres:15
    container_name: fynora-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fynora_db
    ports:
      - "5432:5432"